---
- name: AWX | preparar inventario para instalação
  lineinfile:
    path: "{{ installers_dir }}/awx/installer/inventory"
    regexp: '^awx_official='
    line: 'awx_official=true'

#- name: AWX | Ajustar para usar imagem base do dockerhub
#  blockinfine:
#    path: "{{ installers_dir }}/awx/installer/inventory"
#    block: |
#      dockerhub_base=ansible
#      dockerhub_version=latest

- name: AWX | Executa comando de instalação do AWX
  shell: ansible-playbook -i inventory install.yml
  args:
    chdir: "{{ installers_dir }}/awx/installer"
