---
- name: AWX | Setup inventory options
  lineinfile:
    path: "{{ installer_dir }}/awx/installer/inventory"
    regexp: '^awx_official='
    line: 'awx_official=true'

#- name: AWX | Use official docker hub image
#  blockinfine:
#    path: "{{ installer_dir }}/awx/installer/inventory"
#    block: |
#      dockerhub_base=ansible
#      dockerhub_version=latest

- name: AWX | Run AWX installer
  shell: ansible-playbook -i inventory install.yml
  args:
    chdir: "{{ installer_dir }}/awx/installer"
