---
- name: Create installers dir
  file:
    path: "{{ installers_dir }}"
    state: directory

- name: AWX | clone awx git repo
  git:
    repo: https://github.com/ansible/awx.git
    dest: "{{ installer_dir }}/awx"

- name: AWX | clone awx-logos git repo
  git:
    repo: https://github.com/ansible/awx-logos.git
    dest: "{{ installer_dir }}/awx/awx-logos"
